### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by mpetri** [maekawatoshiki/altius#6]
Hello!

was looking to play with this as part of a larger rust program. Is it possible to publish the core to crates.io so I can import the inference part of this and build my own tooling around it?

**Comment by maekawatoshiki** [comment]
It is possible to publish altius to crates.io, but I'm afraid to do that since it's still in the early stage of development.

How about importing altius from GitHub? `Cargo.toml` like:

```toml
altius-core = { git = "https://github.com/maekawatoshiki/altius.git" }
altius-session = { git = "https://github.com/maekawatoshiki/altius.git", features = ["blis"] }
```
